database:
  host: ${DB_HOST}
  port: ${DB_PORT}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  database: ${DB_NAME}
  charset: ${DB_CHARSET}

app:
  debug: true
  host: 0.0.0.0
  port: 5000