name: ECS Stable Deploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 327030626840

  ECR_REPOSITORY: lab4-v3-app
  ECS_CLUSTER: lab4-cluster
  ECS_SERVICE: lab4-service
  ECS_TASK_FAMILY: lab4-task

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push image (immutable)
      run: |
        IMAGE_TAG=${GITHUB_SHA::8}
        IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

        docker build --no-cache -t $IMAGE_URI .
        docker push $IMAGE_URI

        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

    - name: Download task definition
      run: |
        aws ecs describe-task-definition \
          --task-definition $ECS_TASK_FAMILY \
          --query taskDefinition > task-def.json

    - name: Render new task definition
      run: |
        jq '.containerDefinitions[0].image = env.IMAGE_URI
            | del(
              .taskDefinitionArn,
              .revision,
              .status,
              .requiresAttributes,
              .compatibilities,
              .registeredAt,
              .registeredBy
            )' task-def.json > new-task-def.json

    - name: Register task definition
      run: |
        aws ecs register-task-definition \
          --cli-input-json file://new-task-def.json

    - name: Deploy new revision
      run: |
        aws ecs update-service \
          --cluster $ECS_CLUSTER \
          --service $ECS_SERVICE \
          --force-new-deployment
